### ISSUE TITLE
Stops working on forbidden drop

### ISSUE THREAD

**Issue by Der-Schubi** [SanderRonde/Octoprint-Draggable-Files#8]
When dropping a file to the empty background, the plugin stops working. Only F5 is helping.

**Comment by SanderRonde** [comment]
I've made some changes that hopefully fix this issue. The tough part is that it doesn't occur all of the time so it's a bit hard to fix. Version 1.1.2 should be live soon and it should fix the issue. Please let me know if it does (or doesn't).

**Comment by Der-Schubi** [comment]
The behaviour is still the same with 1.1.2.
Here is a video, showing what I mean exactly: https://we.tl/t-yZqRbFMCSA

**Comment by SanderRonde** [comment]
Hmm I have encountered this issue myself as well now but it's surprisingly hard to replicate and I guess even harder to fix seeing as I'm using two external libraries (Octoprint and Sortable).  I hope to fix this one day but I'll leave this issue open as long as it's not fixed.

**Comment by Der-Schubi** [comment]
Thanks for the effort!

**Comment by jacopotediosi** [comment]
Since many years have passed, and new versions of Sortable have come out, you might want to try to see if updating it solves this issue

**Comment by Der-Schubi** [comment]
Thanks for coming back on this. But I'm no longer using Octoprint.

**Comment by SanderRonde** [comment]
I've also stopped using it but I'll give it a shot anyways. Not much harm in trying to update sortable. Might take a few weeks for me to find the time but I'll get to it eventually.

**Comment by SanderRonde** [comment]
@jacopotediosi Do you use octoprint and this plugin (semi-)regularly? I don't use octoprint anymore either so I can't really test this that well. If so I could simply drop a zip file here with the new version of sortable. If not then I'd prefer to keep the old version of sortable in the plugin since at least this way it seems to be stable.

**Comment by jacopotediosi** [comment]
Hi @SanderRonde, if you want I can test and propose a PR with the updated version of the library. I use Octoprint and this plugin every day. We may also leave the PR open for a few months, so we can gather feedback from other users as well.

**Comment by SanderRonde** [comment]
Yes that would be amazing! If you need any help do let me know

**Comment by jacopotediosi** [comment]
Hi @SanderRonde,

I checked. No need to update the Sortable library.

When dragging files into forbidden areas, the `_getMoveDestination` function throws, appropriately, the exception `Error("Failed to find destination")`.
It is up to the caller, the `_onMove` function, to implement a try-catch. At that point, there is no need to re-attach the dragListener either.

I just created PR #10, which correctly fixes this issue in my instance with OctoPrint 1.11.0.
Users can test my patch by installing it via the OctoPrint Plugin Manager using the following URL: `https://github.com/jacopotediosi/Octoprint-Draggable-Files/archive/fix-forbidden-drop.zip`

After merging, please remember to update `plugin_version` in `setup.py` and publish a new release.

**Comment by SanderRonde** [comment]
Awesome, thank you so much! I'll publish a new release
